<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>1</string>
    <string>2</string>
    <string>3</string>
    <string>4</string>
    <string>5</string>
    <string>6</string>
    <string>7</string>
    <string>8</string>
  </array>
  <key>name</key>
  <string>Man</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>^.(SH|SS|P|IP|HP|RE|B|I|TP|TH|PD|br|nf|fi)\b</string>
      <key>name</key>
      <string>support</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\\f(B|P)</string>
      <key>name</key>
      <string>entity</string>
    </dict>
    <dict>
      <key>match</key>
      <string>.\\".*</string>
      <key>name</key>
      <string>comment</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(NAME|SYNOPSIS|SYNTAX|AVAILABILITY|DESCRIPTION|OPTIONS|EXAMPLES|NOTES|MESSAGES AND EXIT CALLS|AUTHOR|HISTORY|RESOURCES|FILES|BUGS|CAVEATS|SEE ALSO|LICENSE|HOMEPAGE)</string>
      <key>name</key>
      <string>constant</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\".*\"</string>
      <key>name</key>
      <string>string</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.man</string>
  <key>uuid</key>
  <string>99484479-c4b5-4719-9335-126c523d019d</string>
</dict>
</plist>
