<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>rbdef</string>
  </array>
  <key>firstLineMatch</key>
  <string># RBBuild Def File</string>
  <key>name</key>
  <string>RBDef</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>^(eol|deps|CFLAGS|CPPFLAGS|LDFLAGS|CONFOPTS|MAKEOPTS|INSTOPTS|PREFIX)\(.*\):</string>
      <key>name</key>
      <string>entity</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\{[a-zA-Z0-9_]{3,}\}</string>
      <key>name</key>
      <string>variable</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(package|patch|patchset|git|hg|svn):</string>
      <key>name</key>
      <string>keyword</string>
    </dict>
    <dict>
      <key>match</key>
      <string>^\[.*\]$</string>
      <key>name</key>
      <string>constant</string>
    </dict>
    <dict>
      <key>match</key>
      <string>#.*</string>
      <key>name</key>
      <string>comment</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\".*\"</string>
      <key>name</key>
      <string>string</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\'.*\'</string>
      <key>name</key>
      <string>string</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.rbdef</string>
  <key>uuid</key>
  <string>a3598300-c543-11e3-9c1a-0800200c9a66</string>
</dict>
</plist>
